//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILStubDiagnostic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceStubHelpersAPI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStubHelpersAPI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ILStubDiagnostic.ResourceStubHelpersAPI", typeof(ResourceStubHelpersAPI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.AnsiCharMarshaler::DoAnsiConversion=Convert a managed System.String instance to an Ansi string instance..
        /// </summary>
        internal static string API_000 {
            get {
                return ResourceManager.GetString("API_000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.AnsiCharMarshaler::ConvertToNative=Convert a managed character to an Ansi character..
        /// </summary>
        internal static string API_001 {
            get {
                return ResourceManager.GetString("API_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.AnsiCharMarshaler::ConvertToManaged=Convert an Ansi character character to a managed character..
        /// </summary>
        internal static string API_002 {
            get {
                return ResourceManager.GetString("API_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.CSTRMarshaler::ConvertToNative=Convert a System.String instance to an Ansi string (LPSTR) instance..
        /// </summary>
        internal static string API_003 {
            get {
                return ResourceManager.GetString("API_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.CSTRMarshaler::ConvertToManaged=Convert an Ansi string (LPSTR) instance to a System.String instance..
        /// </summary>
        internal static string API_004 {
            get {
                return ResourceManager.GetString("API_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.CSTRMarshaler::ClearNative=Free the memory used in the marshaler..
        /// </summary>
        internal static string API_005 {
            get {
                return ResourceManager.GetString("API_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.BSTRMarshaler::ConvertToNative=Convert a System.String instance to a BSTR instance..
        /// </summary>
        internal static string API_006 {
            get {
                return ResourceManager.GetString("API_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.BSTRMarshaler::ConvertToManaged=Convert a BSTR instance to a System.String instance..
        /// </summary>
        internal static string API_007 {
            get {
                return ResourceManager.GetString("API_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.BSTRMarshaler::ClearNative=Free the memory used in the marshaler..
        /// </summary>
        internal static string API_008 {
            get {
                return ResourceManager.GetString("API_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.VBByValStrMarshaler::ConvertToNative=Convert a System.String instance to VBByRefStr instance..
        /// </summary>
        internal static string API_009 {
            get {
                return ResourceManager.GetString("API_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.VBByValStrMarshaler::ConvertToManaged=Convert a VBByRefStr instance to a System.String instance..
        /// </summary>
        internal static string API_010 {
            get {
                return ResourceManager.GetString("API_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.VBByValStrMarshaler::ClearNative=Free the memory used in the marshaler..
        /// </summary>
        internal static string API_011 {
            get {
                return ResourceManager.GetString("API_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.AnsiBSTRMarshaler::ConvertToNative=Convert a System.String instance to an Ansi BSTR instance..
        /// </summary>
        internal static string API_012 {
            get {
                return ResourceManager.GetString("API_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.AnsiBSTRMarshaler::ConvertToManaged=Convert an Ansi BSTR instance to a System.String instance..
        /// </summary>
        internal static string API_013 {
            get {
                return ResourceManager.GetString("API_013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.AnsiBSTRMarshaler::ClearNative=Free the memory used in the marshaler..
        /// </summary>
        internal static string API_014 {
            get {
                return ResourceManager.GetString("API_014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.WSTRBufferMarshaler::ConvertToNative=Convert a System.String instance to a LPWSTR instance. This function should not be invoked..
        /// </summary>
        internal static string API_015 {
            get {
                return ResourceManager.GetString("API_015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.WSTRBufferMarshaler::ConvertToManaged=Convert a LPWSTR instance to a System.String instance. This function should not be invoked..
        /// </summary>
        internal static string API_016 {
            get {
                return ResourceManager.GetString("API_016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.WSTRBufferMarshaler::ConvertToClearNative=Free the memory used in the marshaler. This function should not be invoked..
        /// </summary>
        internal static string API_017 {
            get {
                return ResourceManager.GetString("API_017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.ObjectMarshaler::ConvertToNative=Convert a System.Object instance to a native representation, which could be IUnknown, IDispatch, VARIANT, struct, and so on..
        /// </summary>
        internal static string API_018 {
            get {
                return ResourceManager.GetString("API_018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.ObjectMarshaler::ConvertToManaged=Convert a native data type instance, for example IUnknown, IDispatch VARIANT, struct,  to a System.Object instance..
        /// </summary>
        internal static string API_019 {
            get {
                return ResourceManager.GetString("API_019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.ObjectMarshaler::ClearNative=Free the memory used in the marshaler..
        /// </summary>
        internal static string API_020 {
            get {
                return ResourceManager.GetString("API_020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.ValueClassMarshaler::ConvertToNative=Convert a managed struct instance to a native struct instance..
        /// </summary>
        internal static string API_021 {
            get {
                return ResourceManager.GetString("API_021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.ValueClassMarshaler::ConvertToManaged=Convert a native struct instance to a managed struct instance..
        /// </summary>
        internal static string API_022 {
            get {
                return ResourceManager.GetString("API_022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.ValueClassMarshaler::ClearNative=Free the memory used in the marshaler..
        /// </summary>
        internal static string API_023 {
            get {
                return ResourceManager.GetString("API_023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.DateMarshaler::ConvertToNative=Convert a System.DateTime instance to a DATE type instance. DATE type is actually float..
        /// </summary>
        internal static string API_024 {
            get {
                return ResourceManager.GetString("API_024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.DateMarshaler::ConvertToManaged=Convert a DATE type instance to a System.DateTime instance. This function returns int64 value for System.DateTime..
        /// </summary>
        internal static string API_025 {
            get {
                return ResourceManager.GetString("API_025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.InterfaceMarshaler::ConvertToNative=Convert a managed object to a COM interface pointer..
        /// </summary>
        internal static string API_026 {
            get {
                return ResourceManager.GetString("API_026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.InterfaceMarshaler::ConvertToManaged=Convert a COM interface pointer to a managed object..
        /// </summary>
        internal static string API_027 {
            get {
                return ResourceManager.GetString("API_027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.InterfaceMarshaler::ClearNative=Free the memory used in the marshaler..
        /// </summary>
        internal static string API_028 {
            get {
                return ResourceManager.GetString("API_028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.MngdNativeArrayMarshaler::CreateMarshaler=Initialize a native array marshaler to convert a native array to a managed array or a managed array to a native array..
        /// </summary>
        internal static string API_029 {
            get {
                return ResourceManager.GetString("API_029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.MngdNativeArrayMarshaler::ConvertSpaceToNative=Allocate memory for a native array..
        /// </summary>
        internal static string API_030 {
            get {
                return ResourceManager.GetString("API_030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.MngdNativeArrayMarshaler::ConvertContentsToNative=Convert contents of a managed array to a native array..
        /// </summary>
        internal static string API_031 {
            get {
                return ResourceManager.GetString("API_031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.MngdNativeArrayMarshaler::ConvertSpaceToManaged=Allocate memory for a managed array..
        /// </summary>
        internal static string API_032 {
            get {
                return ResourceManager.GetString("API_032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.MngdNativeArrayMarshaler::ConvertContentsToManaged=Convert contents of a native array to a managed array..
        /// </summary>
        internal static string API_033 {
            get {
                return ResourceManager.GetString("API_033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.MngdNativeArrayMarshaler::ClearNative=Free the memory used in the marshaler..
        /// </summary>
        internal static string API_034 {
            get {
                return ResourceManager.GetString("API_034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.MngdNativeArrayMarshaler::ClearNativeContents=Free the memory used in the marshaler..
        /// </summary>
        internal static string API_035 {
            get {
                return ResourceManager.GetString("API_035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.MngdSafeArrayMarshaler::CreateMarshaler=Initialize a safe array marshaler to convert a safe array to a managed array or a managed array to a safe array..
        /// </summary>
        internal static string API_036 {
            get {
                return ResourceManager.GetString("API_036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.MngdSafeArrayMarshaler::ConvertSpaceToNative=Allocate memory for a safe array..
        /// </summary>
        internal static string API_037 {
            get {
                return ResourceManager.GetString("API_037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.MngdSafeArrayMarshaler::ConvertContentsToNative=Convert contents of a managed array to a safe array..
        /// </summary>
        internal static string API_038 {
            get {
                return ResourceManager.GetString("API_038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.MngdSafeArrayMarshaler::ConvertSpaceToManaged=Allocate memory for a managed array..
        /// </summary>
        internal static string API_039 {
            get {
                return ResourceManager.GetString("API_039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.MngdSafeArrayMarshaler::ConvertContentsToManaged=Convert contents of a safe array to a managed array..
        /// </summary>
        internal static string API_040 {
            get {
                return ResourceManager.GetString("API_040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.MngdSafeArrayMarshaler::ClearNative=Free the memory used in the marshaler..
        /// </summary>
        internal static string API_041 {
            get {
                return ResourceManager.GetString("API_041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.MngdRefCustomMarshaler::CreateMarshaler=Set the custom marshaler..
        /// </summary>
        internal static string API_042 {
            get {
                return ResourceManager.GetString("API_042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.MngdRefCustomMarshaler::ConvertContentsToNative=Use custom marshaler to convert managed contents to native contents..
        /// </summary>
        internal static string API_043 {
            get {
                return ResourceManager.GetString("API_043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.MngdRefCustomMarshaler::ConvertContentsToManaged=Use custom marshaler to convert native contents to managed contents..
        /// </summary>
        internal static string API_044 {
            get {
                return ResourceManager.GetString("API_044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.MngdRefCustomMarshaler::ClearNative=Free the memory used in the marshaler..
        /// </summary>
        internal static string API_045 {
            get {
                return ResourceManager.GetString("API_045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.MngdRefCustomMarshaler::ClearManaged=Free the memory used in the marshaler..
        /// </summary>
        internal static string API_046 {
            get {
                return ResourceManager.GetString("API_046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.AsAnyMarshaler::ConvertToNative=Convert a System.Object instance with &apos;MarshalAs(UnmanagedType.AsAny)&apos; attribute to the native representation..
        /// </summary>
        internal static string API_047 {
            get {
                return ResourceManager.GetString("API_047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.AsAnyMarshaler::ConvertToManaged=Convert a native data type to a System.Object instance with &apos;MarshalAs(UnmanagedType.AsAny)&apos; attribute..
        /// </summary>
        internal static string API_048 {
            get {
                return ResourceManager.GetString("API_048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.AsAnyMarshaler::ClearNative=Free the memory used in the marshaler..
        /// </summary>
        internal static string API_049 {
            get {
                return ResourceManager.GetString("API_049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.EEFrame::Push=.
        /// </summary>
        internal static string API_050 {
            get {
                return ResourceManager.GetString("API_050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.EEFrame::Pop=.
        /// </summary>
        internal static string API_051 {
            get {
                return ResourceManager.GetString("API_051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.CleanupWorkList::Add=.
        /// </summary>
        internal static string API_052 {
            get {
                return ResourceManager.GetString("API_052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.CleanupWorkList::Destroy=.
        /// </summary>
        internal static string API_053 {
            get {
                return ResourceManager.GetString("API_053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::IsQCall=.
        /// </summary>
        internal static string API_054 {
            get {
                return ResourceManager.GetString("API_054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::InitDeclaringType=.
        /// </summary>
        internal static string API_055 {
            get {
                return ResourceManager.GetString("API_055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::GetNDirectTarget=.
        /// </summary>
        internal static string API_056 {
            get {
                return ResourceManager.GetString("API_056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::GetDelegateTarget=.
        /// </summary>
        internal static string API_057 {
            get {
                return ResourceManager.GetString("API_057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::Verify__EEFrame__Pop=.
        /// </summary>
        internal static string API_058 {
            get {
                return ResourceManager.GetString("API_058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::Verify__EEFrame__Push=.
        /// </summary>
        internal static string API_059 {
            get {
                return ResourceManager.GetString("API_059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::GetProcessGSCookie=.
        /// </summary>
        internal static string API_060 {
            get {
                return ResourceManager.GetString("API_060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::FailFast=.
        /// </summary>
        internal static string API_061 {
            get {
                return ResourceManager.GetString("API_061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::DoNDirectCall=.
        /// </summary>
        internal static string API_062 {
            get {
                return ResourceManager.GetString("API_062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::DoCLRToCOMCall=.
        /// </summary>
        internal static string API_063 {
            get {
                return ResourceManager.GetString("API_063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::BeginStandalone=.
        /// </summary>
        internal static string API_064 {
            get {
                return ResourceManager.GetString("API_064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::BeginCLRToCOMStandalone=.
        /// </summary>
        internal static string API_065 {
            get {
                return ResourceManager.GetString("API_065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::DemandPermission=.
        /// </summary>
        internal static string API_066 {
            get {
                return ResourceManager.GetString("API_066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::SetLastError=.
        /// </summary>
        internal static string API_067 {
            get {
                return ResourceManager.GetString("API_067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::ThrowDeferredException=.
        /// </summary>
        internal static string API_068 {
            get {
                return ResourceManager.GetString("API_068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::ThrowInteropParamException=.
        /// </summary>
        internal static string API_069 {
            get {
                return ResourceManager.GetString("API_069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::AddToCleanupList=.
        /// </summary>
        internal static string API_070 {
            get {
                return ResourceManager.GetString("API_070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::DestroyCleanupList=.
        /// </summary>
        internal static string API_071 {
            get {
                return ResourceManager.GetString("API_071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::GetHRExceptionObject=.
        /// </summary>
        internal static string API_072 {
            get {
                return ResourceManager.GetString("API_072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::InternalGetHRExceptionObject=.
        /// </summary>
        internal static string API_073 {
            get {
                return ResourceManager.GetString("API_073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::GetCOMHRExceptionObject=.
        /// </summary>
        internal static string API_074 {
            get {
                return ResourceManager.GetString("API_074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::InternalGetCOMHRExceptionObject=.
        /// </summary>
        internal static string API_075 {
            get {
                return ResourceManager.GetString("API_075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::CreateCustomMarshalerHelper=.
        /// </summary>
        internal static string API_076 {
            get {
                return ResourceManager.GetString("API_076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::SafeHandleAddRef=.
        /// </summary>
        internal static string API_077 {
            get {
                return ResourceManager.GetString("API_077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::SafeHandleRelease=.
        /// </summary>
        internal static string API_078 {
            get {
                return ResourceManager.GetString("API_078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::GetCLRToCOMTarget=.
        /// </summary>
        internal static string API_079 {
            get {
                return ResourceManager.GetString("API_079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::GetCOMIPFromRCW=.
        /// </summary>
        internal static string API_080 {
            get {
                return ResourceManager.GetString("API_080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::StubRegisterRCW=.
        /// </summary>
        internal static string API_081 {
            get {
                return ResourceManager.GetString("API_081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::StubUnregisterRCW=.
        /// </summary>
        internal static string API_082 {
            get {
                return ResourceManager.GetString("API_082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::ProfilerBeginTransitionCallback=.
        /// </summary>
        internal static string API_083 {
            get {
                return ResourceManager.GetString("API_083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::ProfilerEndTransitionCallback=.
        /// </summary>
        internal static string API_084 {
            get {
                return ResourceManager.GetString("API_084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::DebuggerTraceCall=.
        /// </summary>
        internal static string API_085 {
            get {
                return ResourceManager.GetString("API_085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::CheckStringLength=.
        /// </summary>
        internal static string API_086 {
            get {
                return ResourceManager.GetString("API_086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::strlen=.
        /// </summary>
        internal static string API_087 {
            get {
                return ResourceManager.GetString("API_087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::DecimalCanonicalizeInternal=.
        /// </summary>
        internal static string API_088 {
            get {
                return ResourceManager.GetString("API_088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::FmtClassUpdateNativeInternal=.
        /// </summary>
        internal static string API_089 {
            get {
                return ResourceManager.GetString("API_089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::FmtClassUpdateCLRInternal=.
        /// </summary>
        internal static string API_090 {
            get {
                return ResourceManager.GetString("API_090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::LayoutDestroyNativeInternal=.
        /// </summary>
        internal static string API_091 {
            get {
                return ResourceManager.GetString("API_091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::AllocateInternal=.
        /// </summary>
        internal static string API_092 {
            get {
                return ResourceManager.GetString("API_092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::MarshalToUnmanagedVaListInternal=.
        /// </summary>
        internal static string API_093 {
            get {
                return ResourceManager.GetString("API_093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::MarshalToManagedVaListInternal=.
        /// </summary>
        internal static string API_094 {
            get {
                return ResourceManager.GetString("API_094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.StubHelpers.StubHelpers::GetStubContext=.
        /// </summary>
        internal static string API_095 {
            get {
                return ResourceManager.GetString("API_095", resourceCulture);
            }
        }
    }
}
